export const foods = [
  {
    id: 1,
    icon: "soup_kitchen",
    name: "Egusi Soup",
    description: "Served with choice of Eba, Pounded Yam, or Fufu.",
    price: 3500,
    category: "Soups & Swallows",
  },
  {
    id: 2,
    icon: "rice_bowl",
    name: "Jollof Rice",
    description: "Classic smoky party jollof with fried plantains.",
    price: 2500,
    category: "Rice Dishes",
  },
  {
    id: 3,
    icon: "kebab_dining",
    name: "Peppered Goat Meat",
    description: "Spicy grilled goat meat chunks.",
    price: 1200,
    unit: "stick",
    category: "Proteins",
  },
  {
    id: 4,
    icon: "bakery_dining",
    name: "Puff Puff",
    description: "Sweet, deep-fried dough balls.",
    price: 1000,
    unit: "6 pcs",
    category: "Small Chops",
  },
  {
    id: 5,
    icon: "local_bar",
    name: "Chapman",
    description: "Refreshing Nigerian mocktail with bitters.",
    price: 1500,
    category: "Drinks",
  },
  {
    id: 6,
    icon: "outdoor_grill",
    name: "Beef Suya",
    description: "Spicy skewered beef with yaji spice.",
    price: 2000,
    unit: "wrap",
    category: "Proteins",
  },
];
export const categories = [
  "All",
  "Rice Dishes",
  "Proteins",
  "Small Chops",
  "Drinks",
];
export const bulkItems = [
  {
    id: 1,
    icon: "rice_bowl",
    name: "Party Jollof Rice",
    description: "Signature smoky jollof rice served with fried plantains.",
    price: 3500,
    category: "Rice Dishes",
  },
  {
    id: 2,
    icon: "soup_kitchen",
    name: "Egusi Soup & Pounded Yam",
    description: "Rich melon seed soup with spinach and assorted meats.",
    price: 4500,
    category: "Soups & Swallows",
  },
  {
    id: 3,
    icon: "kebab_dining",
    name: "Spicy Beef Suya",
    description: "Thinly sliced grilled beef coated in fiery peanut spice mix.",
    price: 2000,
    category: "Proteins",
  },
];
